### ISSUE TITLE
Some parts showing as "null"

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_lscustom#26]
The parts works fine it just show "null" with some of them.
![Skærmbillede 2023-09-17 221121](https://github.com/esx-framework/esx_lscustom/assets/36231983/b3b2a823-49e2-48fe-8669-16102853204e)

**Comment by thesysadmindev** [comment]
@NexDK this isn't a bug with esx_lscustom. You will need to seek support on how to add these names in as they are related to vehicle parts included with the vehicles used.

**Comment by NexDK** [comment]
@thesysadmindev should it not work with the original gta cars, i don't use addon cars ?

**Comment by bitpredator** [comment]
> @NexDK this isn't a bug with esx_lscustom. You will need to seek support on how to add these names in as they are related to vehicle parts included with the vehicles used.

Exactly, I tried to insert a custom car and the extra accessories are displayed as "NULL", I recommend creating documentation on how to insert extra accessories in esx_lscustom.
