### ISSUE TITLE
Vehicle Extras being reset when entering ls customs

### ISSUE THREAD

**Issue by 146Codes** [esx-framework/esx_lscustom#32]
The problem is that, if you enter ls customs, as soon as you chosse the Category Upgrades or Extras it will load some kind of default vlaue of extras of the vehicle, if you leave at that point the extras stay like this, if you enter again and choose one of the two categories the extras are reset to the values they should be and also stay like that when leaving!

Edit: Just entering and instantly leaving also does this (dont need to chosse a category)

A video to demonstrate this: https://medal.tv/games/gta-v/clips/jb37aqsYLwhyVU3OH?invite=cr-MSxwQXYsMTgwNTM0NDc2LA

**Comment by Kenshiin13** [comment]
This has already been fixed on dev branch in [esx_core#1504](https://github.com/esx-framework/esx_core/pull/1504).
